
#define IDCOMPILE                       3
#define IDLINK							4

#define IDD_DSP_LINK                    130
#define IDD_DSP_ASM                     131
#define IDC_SOURCEFILENAME              1000
#define IDC_SOURCEPATHNAME              1000
#define IDC_READLISTFILE                1001
#define IDC_PROJECTNAME                 1001
#define IDC_DEBUGFILENAME               1002
#define IDC_COMPILE_MSG                 1003
#define IDC_LISTFILENAME                1004
#define IDC_CODEFILENAME                1005
#define IDC_CHECK1                      1006
#define IDC_CHECK2                      1007
#define IDC_CHECK3                      1008
#define IDC_CHECK4                      1009

